# Generated by Django 3.2.7 on 2021-09-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='account_No',
            field=models.CharField(default='673872394219', max_length=255),
        ),
        migrations.AlterField(
            model_name='register',
            name='routine',
            field=models.CharField(default='071925444', max_length=255),
        ),
    ]
